### ISSUE TITLE
Support for Python 3.10+

### ISSUE THREAD

**Issue by willi-z** [akaszynski/ansys_corba#2]
Hi Alex,

I used pymapdl back then, when it was still in its infancy and love what it has become! 
With pyansys now supporting python versions up to 3.10 is it possible to upgrade the avaible python versions for cobra to evade python interpreter mismatch?

Best Regards

Willi

**Comment by akaszynski** [comment]
Hi @willi-z,

We've since updated our RPC interface to use gRPC rather than CORBA, and as such we're no longer actively developing the `ansys_corba` interface.
