### ISSUE TITLE
Changing the Simulation Enviroment

### ISSUE THREAD

**Issue by willi-z** [akaszynski/ansys_corba#3]
Hi Alex,

the APDL Product launcher has the option to change the "Simulation Environment".
Does Cobra support this option too?
Since LS-Dyna is now an ANSYS-Product I was woundering if pymapdl will support it in the future, or at least give users a plattform to build uppon their costum solution for automating simulation workflows.

Best Regards
Willi

**Comment by akaszynski** [comment]
Hi @willi-z,

I can promise you (though without giving any specifics) that there are going to be several new Python client libraries coming out in the near term (i.e. end of the year). One of those will likely directly support this request.
